app/biosphere/BiosphereWebApplication/Models/ErrorViewModel.cs
using System;

namespace BiosphereWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

app/biosphere/BiosphereWebApplication/Controllers/DevController.cs
using Microsoft.AspNetCore.Mvc;

namespace BiosphereWebApplication.Controllers
{
    public class DevController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SimpleMap()
        {
            return View();
        }

        public IActionResult AnimalAnimation()
        {
            return View();
        }

        public IActionResult GUITest()
        {
            return View();
        }

        public IActionResult BushGrowing()
        {
            return View();
        }
    }
}

app/biosphere/BiosphereWebApplication/Controllers/HomeController.cs
using BiosphereWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BiosphereWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

app/biosphere/BiosphereWebApplication/Controllers/TechDemoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BiosphereWebApplication.Controllers
{
    public class TechDemoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

app/biosphere/BiosphereWebApplication/Views/Dev/AnimalAnimation.cshtml
<div class="k-content wide">
    <div id="toolbar"></div>
</div>
<div id="renderPlaceholder">
</div>

<script>
    $(document).ready(function() {
        $("#toolbar").kendoToolBar({
            items: [
                { template: "<label for='animalList'>Animal:</label>" },
                {
                    template: "<input id='animalList' style='width: 150px;' />",
                    overflow: "never"
                }
            ]
        });

        $("#animalList").kendoDropDownList({
            dataTextField: "text",
            dataValueField: "value",
            dataSource: animalData,
            change: function(e) {
                currentSprite = this.value();
                printCurrentAnimal();
            }
        });
    });
</script>

@section ScriptInBody
{
    <script>
        var animal = null;
        var cursors = null;
        var currentSprite = "sheep";
        var animalLabel = null;

        var animalData = [
            { text: "Sheep", value: "sheep" },
            { text: "Cow", value: "cow" }
        ];

        var config = {
            type: Phaser.AUTO,
            width: 1200,
            height: 500,
            backgroundColor: "#458f56",
            physics: {
                default: "arcade",
                arcade: {
                    debug: false
                }
            },
            scene: {
                preload: preload,
                create: create,
                update: update
            },
            parent: "renderPlaceholder"
        };

        var game = new Phaser.Game(config);

        function preload () {
            this.load.path = commonscripts.getAssetsPath();
            for (let i = 0; i < animalData.length; i++) {
                let spriteName = animalData[i].value;
                this.load.spritesheet(spriteName, `/animals/${spriteName}_sprite/${spriteName}.png`, { frameWidth: 128, frameHeight: 128 }); //"/animals/animal_sprite/animal.json"
            }
        }

        function create ()
        {
            let help = this.add.text(16, 16, "[Arrows] to move the animal. [Space] to stop it. Click outside of the dropdown to apply changes.", { fontSize: "18px", fill: "#ffffff" });
            animalLabel = this.add.text(16, 48, "Unknown Animal", {fontSize: "18px", fill: "#ffffff" });
            printCurrentAnimal();
            animalLabel.setScrollFactor(0);
            help.setScrollFactor(0);

            animal = this.physics.add.sprite(100, 100, currentSprite); //generic sprite for all types of animal
            animal.setBounce(0.2);
            animal.setCollideWorldBounds(true);

            //create animation for all animals
            const fRate = 7;
            for (let i = 0; i < animalData.length; i++) {
                let spriteName = animalData[i].value;
                this.anims.create({
                    key: spriteName + "_up",
                    frames: this.anims.generateFrameNumbers(spriteName, { start: 0, end: 3 }),
                    frameRate: fRate,
                    repeat: -1
                });

                this.anims.create({
                    key: spriteName + "_left",
                    frames: this.anims.generateFrameNumbers(spriteName, { start: 4, end: 7 }),
                    frameRate: fRate,
                    repeat: -1
                });

                this.anims.create({
                    key: spriteName + "_down",
                    frames: this.anims.generateFrameNumbers(spriteName, { start: 8, end: 11 }),
                    frameRate: fRate,
                    repeat: -1
                });

                this.anims.create({
                    key: spriteName + "_right",
                    frames: this.anims.generateFrameNumbers(spriteName, { start: 12, end: 15 }),
                    frameRate: fRate,
                    repeat: -1
                });
            }

            cursors = this.input.keyboard.createCursorKeys();
        }

        function update () {
            const speed = 50;

            if (cursors.up.isDown)
            {
                animal.setVelocityY(-speed);
                animal.anims.play(currentSprite + "_up", true);
            }
            else if (cursors.left.isDown)
            {
                animal.setVelocityX(-speed);
                animal.anims.play(currentSprite + "_left", true);
            }
            else if (cursors.down.isDown) {
                animal.setVelocityY(speed);
                animal.anims.play(currentSprite + "_down", true);
            }
            else if (cursors.right.isDown) {
                animal.setVelocityX(speed);
                animal.anims.play(currentSprite + "_right", true);
            }
            else if (cursors.space.isDown) {
                animal.setVelocityX(0);
                animal.setVelocityY(0);
                animal.anims.stop();
            }
        }

        function printCurrentAnimal() {
            animalLabel.text = `Animal: ${currentSprite}`;
        }

    </script>
}

app/biosphere/BiosphereWebApplication/Views/Dev/BushGrowing.cshtml
<div class="k-content wide">
    <input id="slider" style="width: 50%" value="0" />
</div>
<div id="renderPlaceholder">
</div>

<script>
    $(document).ready(function () {
        let step = (maxSize - minSize) * Math.pow(10, -1);
        $("#slider").kendoSlider({
            //increaseButtonTitle: "Right",
            //decreaseButtonTitle: "Left",
            min: minSize,
            max: maxSize,
            smallStep: step,
            //largeStep: 1,
            change: function (e) {
                sizeLabel.text = `Size: ${e.value}`;
                for (let i = 0; i < sprites.length; i++) {
                    sprites[i].setScale(e.value);
                }
            },
            value: minSize
        }).data("kendoSlider");
    });
</script>

@section ScriptInBody
{
    <script>
        var sizeLabel = null;
        var sprites = [];
        const minSize = 0.0625;
        const maxSize = 0.125;

        var config = {
            type: Phaser.AUTO,
            width: 1200,
            height: 500,
            backgroundColor: "#458f56",
            physics: {
                default: "arcade",
                arcade: {
                    debug: false
                }
            },
            scene: {
                preload: preload,
                create: create,
                update: update
            },
            parent: "renderPlaceholder"
        };

        var game = new Phaser.Game(config);

        function preload () {
            this.load.path = commonscripts.getAssetsPath();
            for (let i = 1; i <= 4; i++) {
                let spriteName = `Bush (${i})`;
                this.load.image(spriteName, `/objects/${spriteName}.png`);
            }
        }

        function create ()
        {
            sizeLabel = this.add.text(16, 48, "", {fontSize: "18px", fill: "#ffffff" });
            sizeLabel.setScrollFactor(0);

            let xCoord = 10;
            for (let i = 1; i <= 4; i++) {
                //TODO use this.physics.add.staticGroup(); ?
                let sp = this.add.sprite(xCoord, 30, `Bush (${i})`);
                sp.setOrigin(0, 0).setScale(minSize);
                sprites.push(sp);
                
                //.refreshBody()
                xCoord += 250;
            }
        }

        function update () {
            
        }
    </script>
}

app/biosphere/BiosphereWebApplication/Views/Dev/GUITest.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

app/biosphere/BiosphereWebApplication/Views/Dev/Index.cshtml
<p>
    <button type="button" class="btn btn-primary" onclick="$.bstests.runSimpleMap()">Run Simple Map Test</button>
</p>
<p>
    <button type="button" class="btn btn-primary" onclick="$.bstests.runAnimalAnimation()">Run Animal Animation Test</button>
</p>
<p>
    <button type="button" class="btn btn-primary" onclick="$.bstests.runBushGrowing()">Run Bush Growing Test</button>
</p>
<p>
    <button type="button" class="btn btn-primary disabled" onclick="">Generate CSV map</button>
</p>
<p>
    <button type="button" class="btn btn-primary disabled" onclick="">Run GUI Test</button>
</p>


@section Scripts
{
    <script src="~/js/project/bstests.js"></script>
}

app/biosphere/BiosphereWebApplication/Views/Dev/SimpleMap.cshtml
@section ScriptInBody
{
    <script>
        var config = {
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            backgroundColor: "#2d2d2d",
            parent: "phaser-example",
            pixelArt: true,
            scene: {
                preload: preload,
                create: create,
                update: update
            }
        };

        var controls;

        var game = new Phaser.Game(config);

        function preload() {
            this.load.path = commonscripts.getAssetsPath();
            this.load.tilemapCSV("map", "/maps/simple.csv");
            this.load.image("ground", "/ground/ground.png");
        }

        function create () {
            console.log(this.cache.tilemap.entries);
            // When loading a CSV map, make sure to specify the tileWidth and tileHeight
            var map = this.make.tilemap({ key: "map", tileWidth: 256, tileHeight: 256 });
            var tileset = map.addTilesetImage("ground");
            var layer = map.createLayer(0, tileset, 0, 0); // layer index, tileset, x, y
            layer.skipCull = true;

            this.cameras.main.setBounds(0, 0, map.widthInPixels, map.heightInPixels);

            var cursors = this.input.keyboard.createCursorKeys();

            var controlConfig = {
                camera: this.cameras.main,
                left: cursors.left,
                right: cursors.right,
                up: cursors.up,
                down: cursors.down,
                speed: 0.5
            };

            controls = new Phaser.Cameras.Controls.FixedKeyControl(controlConfig);

            var help = this.add.text(16, 16, "Arrow keys to scroll", {
                fontSize: "18px",
                fill: "#ffffff"
            });

            help.setScrollFactor(0);

            //var gui = new dat.GUI();

            var cam = this.cameras.main;

            cam.setBounds(0, 0, 4096, 4096);

            /*
            gui.addFolder("Camera");
            gui.add(cam, "dirty").listen();
            gui.add(cam.midPoint, "x").listen();
            gui.add(cam.midPoint, "y").listen();
            gui.add(cam, "scrollX").listen();
            gui.add(cam, "scrollY").listen();
            */
        }

        function update (time, delta)
        {
            controls.update(delta);
        }

    </script>
}

app/biosphere/BiosphereWebApplication/Views/Dev/SimpleMapTest.cshtml
@section ScriptInBody
{
    <script>
        var config = {
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            backgroundColor: "#2d2d2d",
            parent: "phaser-example",
            pixelArt: true,
            scene: {
                preload: preload,
                create: create,
                update: update
            }
        };

        var controls;

        var game = new Phaser.Game(config);

        function preload() {
            this.load.path = commonscripts.getAssetsPath();
            this.load.tilemapCSV("map", "/maps/simple.csv");
            this.load.image("ground", "/ground/ground.png");
        }

        function create () {
            console.log(this.cache.tilemap.entries);
            // When loading a CSV map, make sure to specify the tileWidth and tileHeight
            var map = this.make.tilemap({ key: "map", tileWidth: 256, tileHeight: 256 });
            var tileset = map.addTilesetImage("ground");
            var layer = map.createLayer(0, tileset, 0, 0); // layer index, tileset, x, y
            layer.skipCull = true;

            this.cameras.main.setBounds(0, 0, map.widthInPixels, map.heightInPixels);

            var cursors = this.input.keyboard.createCursorKeys();

            var controlConfig = {
                camera: this.cameras.main,
                left: cursors.left,
                right: cursors.right,
                up: cursors.up,
                down: cursors.down,
                speed: 0.5
            };

            controls = new Phaser.Cameras.Controls.FixedKeyControl(controlConfig);

            var help = this.add.text(16, 16, "Arrow keys to scroll", {
                fontSize: "18px",
                fill: "#ffffff"
            });

            help.setScrollFactor(0);

            //var gui = new dat.GUI();

            var cam = this.cameras.main;

            cam.setBounds(0, 0, 4096, 4096);

            /*
            gui.addFolder("Camera");
            gui.add(cam, "dirty").listen();
            gui.add(cam.midPoint, "x").listen();
            gui.add(cam.midPoint, "y").listen();
            gui.add(cam, "scrollX").listen();
            gui.add(cam, "scrollY").listen();
            */
        }

        function update (time, delta)
        {
            controls.update(delta);
        }

    </script>
}

app/biosphere/BiosphereWebApplication/Views/Home/Index.cshtml
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Welcome to Biosphere!</h1>
        <p class="lead">This is a game about creating ecosystems.</p>
    </div>
</div>

<div class="m-t-20">
    <button type="button" class="btn btn-primary btn-lg">Create a New World</button>
    <button type="button" class="btn btn-primary btn-lg m-l-10">Open My World</button>

    @*TODO show in DEV mode only*@
    <button type="button" class="btn btn-success btn-lg m-l-10" onclick="$.bsproject.runDevDashboard()">Dev Dashboard</button>
</div>

app/biosphere/BiosphereWebApplication/Views/Shared/MainMenu.cshtml
<header role="navigation">
    <nav class="navbar navbar-expand-lg bg-light nav-pills nav-fill">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            Biosphere
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navBarNavAltMarkup" aria-controls="navBarNavAltMarkup" area-expanded="false" area-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navBarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" asp-area="" asp-controller="Home" asp-action="Index">My World</a>
                <a class="nav-item nav-link" asp-area="" asp-controller="Dev" asp-action="Index">Dev</a>
            </div>
        </div>
        <div class="float-right">
            <ul class="navbar-nav">
                @*
                <li class="nav-item">
                    <a class="nav-link" asp-area="Identity" asp-controller="Account" asp-action="Index" title="@User.SadrUserISID()">@User.Identity.Name</a>
                </li>
                <li class="nav-item">
                    <div class="form-inline" asp-area="Identity" asp-controller="Account" asp-action="Logout">
                        <button type="button" class="nav-link btn btn-link text-dark" onclick="projectScripts.logout()">Logout</button>
                    </div>
                </li>
                *@
            </ul>
        </div>
    </nav>
</header>

app/biosphere/BiosphereWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Biosphere</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/themes/lumen.bootstrap.min.css" />*@
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="stylesheet" href="~/css/project.css" />
    <link rel="stylesheet" href="~/lib/kendo/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="~/lib/kendo/styles/kendo.metro.min.css" />
    <link rel="stylesheet" href="~/lib/kendo/styles/kendo.metro.mobile.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/kendo/js/jquery.min.js"></script>
    <script src="~/lib/kendo/js/kendo.all.min.js"></script>

    @*TODO add it on pages which require it*@
    <script src="//cdn.jsdelivr.net/npm/phaser@3.53.1/dist/phaser.min.js"></script>
</head>
<body>
    @await Html.PartialAsync("MainMenu")

    <div style="margin: 5px">
        @RenderBody()

        @RenderSection("ScriptInBody", required: false)
    </div>
            
       
    @*
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Biosphere - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    *@
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <script src="~/js/shared/CommonScripts.js"></script>
    <script src="~/js/project/bsproject.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

app/biosphere/BiosphereWebApplication/Views/TechDemo/Index.cshtml
<script>
    var config = {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        physics: {
            default: 'arcade',
            arcade: {
                gravity: { y: 200 }
            }
        },
        scene: {
            preload: preload,
            create: create
        }
    };

    var game = new Phaser.Game(config);

    function preload ()
    {
        this.load.setPath("assets/techdemo/");

        this.load.image('sky', 'space3.png');
        this.load.image('logo', 'phaser3-logo.png');
        this.load.image('red', 'red.png');
    }

    function create ()
    {
        this.add.image(400, 300, 'sky');

        var particles = this.add.particles('red');

        var emitter = particles.createEmitter({
            speed: 100,
            scale: { start: 1, end: 0 },
            blendMode: 'ADD'
        });

        var logo = this.physics.add.image(400, 100, 'logo');

        logo.setVelocity(100, 200);
        logo.setBounce(1, 1);
        logo.setCollideWorldBounds(true);

        emitter.startFollow(logo);
    }
</script>